services:
  devcontainer:
    build: .
    container_name: flp-rs-playground
    image: docker.io/1ukastesar/fit-flp-rs
    ports:
      - 127.0.0.1:8888:8888
    userns_mode: host
    volumes:
      - .:/workspaces/rs-playground:Z
      - ./work:/home/jovyan/work:Z
      - ./overrides.json:/opt/conda/share/jupyter/lab/settings/overrides.json:ro,Z
      - ./jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py:ro,Z
